# - Find google_test
# Find the native GOOGLE_TEST headers and libraries.
#
#  GOOGLE_TEST_INCLUDE_DIR  - where to find google_test/google_test.h, etc.
#  GOOGLE_TEST_LIBRARIES    - List of libraries when using google_test.
#  GOOGLE_TEST_FOUND        - True if google_test found.

FIND_PATH(GOOGLE_TEST_INCLUDE_DIR google/profiler.h 
    HINTS
    /usr/include
    /usr/local/include
    /opt/include
)

MARK_AS_ADVANCED(GOOGLE_TEST_INCLUDE_DIR)

FIND_LIBRARY(GOOGLE_TEST_LIBRARY NAMES
    gtest
)

FIND_LIBRARY(GOOGLE_TEST_LIBRARY_MAIN NAMES
    gtest_main
)

MARK_AS_ADVANCED(GOOGLE_TEST_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GOOGLE_TEST DEFAULT_MSG GOOGLE_TEST_LIBRARY GOOGLE_TEST_LIBRARY_MAIN GOOGLE_TEST_INCLUDE_DIR)

IF(GOOGLE_TEST_FOUND)
    SET(GOOGLE_TEST_LIBRARY ${GOOGLE_TEST_LIBRARY})
    SET(GOOGLE_TEST_LIBRARY_MAIN ${GOOGLE_TEST_LIBRARY_MAIN})
    SET(GOOGLE_TEST_INCLUDE_DIR ${GOOGLE_TEST_INCLUDE_DIR})
ENDIF(GOOGLE_TEST_FOUND)
